export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsd2Vmb2V0eHB0Ym5qZ21kd2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzA5NDYzMDcsImV4cCI6MTk4NjUyMjMwN30.tOkLo2YYVxVNI4-kSajFaMzpQcqyNlzsmGSEuZLrzJg";

export const SUPABASE_URL = "https://tlwefoetxptbnjgmdwhb.supabase.co";
